apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/sound-jigsaw-465314-s6/secrets/secret1/versions/1"
        path: "k8s.pem"